### ISSUE TITLE
Gentoo arm64 install Failed: downloading stage3 archive for arm64

### ISSUE THREAD

**Issue by caponk12** [meefik/linuxdeploy-cli#13]
Gentoo stage3 archive for arm64 not found when following http://distfiles.gentoo.org/releases/arm/autobuilds/latest-stage3-arm64.txt

Only present in experiment folder http://distfiles.gentoo.org/experimental/arm64/

**Comment by meefik** [comment]
Gentoo is no longer supported on Linux Deploy.
