### ISSUE TITLE
Deployment using METHOD="chroot" fails

### ISSUE THREAD

**Issue by enekux** [meefik/linuxdeploy-cli#2]
Hello I would like to deploy a container using METHOD="chroot".
This is the conf file:
$ linuxdeploy -p linux conf -x
METHOD="chroot"
SOURCE_PATH="http://mirror.yandex.ru/debian/"
DISTRIB="debian"
ARCH="amd64"
SUITE="stretch"
TARGET_PATH="/home/webmaster/linuxdeploy-cli/rootfs/linux"
CHROOT_DIR="/home/webmaster/linuxdeploy-cli/rootfs/linux"
TARGET_TYPE="directory"
USERNAME="webmaster"
INCLUDE="bootstrap"

When I try to do the deployment I get this error:
$ linuxdeploy -p linux deploy
:: Installing bootstrap/rootfs ... 
Checking installation path ... done
Checking file system ... skip
Mounting partitions: 
/ ... fail

What is wrong?

Thank you,

**Comment by enekux** [comment]
$ linuxdeploy -p linux shell -u root
:: Configuring core/mnt ... 
:: Configuring core/net ... 
proot error: unknown option '-l'.
fatal error: see `proot --help`.

**Comment by meefik** [comment]
Linux Delpoy used version 5.1.1 https://github.com/meefik/PRoot/releases/tag/v5.1.1
