### ISSUE TITLE
Fail to run cli.sh 

### ISSUE THREAD

**Issue by yxj-github-437** [meefik/linuxdeploy-cli#28]
`>>> status`
`[19:48:24] /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/files/cli.sh: line 8: 
: not found`
`[19:48:24] /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/files/cli.sh: line 10: 
: not found`
`[19:48:24] /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/files/cli.sh: line 14: 
: not found`
`[19:48:24] /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/files/cli.sh: line 16: {
: not found`
`[19:48:24] -d status`
`[19:48:24] /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/files/cli.sh: line 18: }
: not found`
`[19:48:24] /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/files/cli.sh: line 19: 
: not found`
`[19:48:24] /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/files/cli.sh: line 21: {
: not found`
`[19:48:24] /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: /data/user/0/ru.meefik.linuxdeploy/files/cli.sh: line 41: syntax error: unexpected word (expecting "in")`
`[19:48:24] <<< status`

**Comment by zhouzhiwen2000** [comment]
I ran into the same problem when building it myself.
How did you solve this?

**Comment by zhouzhiwen2000** [comment]
> I ran into the same problem when building it myself. How did you solve this?

I found out that it was the line-endings.
To solve this, simply run
git config --global core.autocrlf  false 
and clone again.
