### ISSUE TITLE
can't start debian

### ISSUE THREAD

**Issue by ibuynewitem** [meefik/linuxdeploy-cli#4]
I have created an debain system by APP in GUI, and I inputed these commands in shell:
          export ENV_DIR=/data/user/0/ru.meefik.linuxdeploy/env/
          cd /data/user/0/ru.meefik.linuxdeploy/env
          linuxdeploy -p linux start
and it shows:
          The container is not mounted.
why???
How do i start the linux i have already created using linuxdeploy-cli, not GUI?

**Comment by meefik** [comment]
Try
```
linuxdeploy -p linux stop -u
linuxdeploy -p linux start -m
linuxdeploy -p linux shell -u root
```
