### ISSUE TITLE
UNABLE to OPEN TERMINAL 

### ISSUE THREAD

**Issue by papppyo** [meefik/linuxdeploy-cli#5]
#### Expected behavior
I was hoping i could launch linux-deploy and open terminal,use the terminal.

#### Actual behavior
Each time i try to launch terminal i get an error message saying  "Error when starting the terminal".

#### How to reproduce
Download linux deploy ,launch it and open menu ,finally punch terminal..

*linux Deploy 2.0.5
* Android 7.0 Nougat

#### Recording Of The Bug  https://youtu.be/HMUeBT1efW0

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@pappy/unable-to-open-terminal">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by DeVvil1** [comment]
Can you try run Ubuntu 17.10 image through Linux deploy?
I mean is it possible to do so?
If I download an image from official site and use via Linux deploy?

**Comment by meefik** [comment]
Linux Deploy uses [Android Terminal Emulator](https://play.google.com/store/apps/details?id=jackpal.androidterm) for this. Also you must be enable the option "Settings -> Apps -> Linux Deploy -> Permissions -> Additional permissions -> Run arbitrary commands in Terminal Emulator".
